# **1️⃣ Imports**

In [29]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

import joblib


# **2️⃣ Load Dataset**

In [30]:
df = pd.read_csv("../../datasets/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

# **3️⃣ Data Cleaning (Based on EDA)**

 **Replace invalid zeros with NaN**

In [31]:
invalid_zero_cols = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)



**Fill missing values with median**

In [32]:
# for col in invalid_zero_cols:
#     df[col].fillna(df[col].median(), inplace=True)

In [33]:
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# **4️⃣ Feature / Target Split**

In [34]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]


# **5️⃣ Train–Test Split**

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# **6️⃣ Train Multiple Models**

### **Logistic Regression**

In [36]:
lr_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=1000,
        solver="liblinear"
    ))
])


In [37]:
lr_pipeline.fit(X_train, y_train)


lr_preds = lr_pipeline.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_preds))
print("\nClassification Report:\n", classification_report(y_test, lr_preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, lr_preds))


Logistic Regression Accuracy: 0.6948051948051948

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.80      0.77       100
           1       0.57      0.50      0.53        54

    accuracy                           0.69       154
   macro avg       0.66      0.65      0.65       154
weighted avg       0.69      0.69      0.69       154


Confusion Matrix:
 [[80 20]
 [27 27]]


In [38]:
joblib.dump(lr_pipeline, "../../models/diabetes_logistic_pipeline.pkl")


['../../models/diabetes_logistic_pipeline.pkl']

### **Random Forest**

In [39]:
rf_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])



In [40]:
rf_pipeline.fit(X_train, y_train)


Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [41]:
rf_preds = rf_pipeline.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_preds))
print("\nClassification Report:\n", classification_report(y_test, rf_preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, rf_preds))


Random Forest Accuracy: 0.7402597402597403

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.84      0.81       100
           1       0.65      0.56      0.60        54

    accuracy                           0.74       154
   macro avg       0.71      0.70      0.70       154
weighted avg       0.73      0.74      0.73       154


Confusion Matrix:
 [[84 16]
 [24 30]]


In [42]:
joblib.dump(rf_pipeline, "../../models/diabetes_rf_pipeline.pkl")


['../../models/diabetes_rf_pipeline.pkl']

# **SVM**

In [43]:
svm_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", SVC(
        kernel="rbf",
        C=1.0,
        gamma="scale",
        probability=True,
        random_state=42
    ))
])


In [44]:
svm_pipeline.fit(X_train, y_train)


Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('model', SVC(probability=True, random_state=42))])

In [45]:
svm_preds = svm_pipeline.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, svm_preds))
print("\nClassification Report:\n", classification_report(y_test, svm_preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, svm_preds))


SVM Accuracy: 0.7402597402597403

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.84      0.81       100
           1       0.65      0.56      0.60        54

    accuracy                           0.74       154
   macro avg       0.71      0.70      0.70       154
weighted avg       0.73      0.74      0.73       154


Confusion Matrix:
 [[84 16]
 [24 30]]


In [46]:
joblib.dump(svm_pipeline, "../../models/diabetes_svm_pipeline.pkl")


['../../models/diabetes_svm_pipeline.pkl']

In [47]:
lr_loaded = joblib.load("../../models/diabetes_logistic_pipeline.pkl")
rf_loaded = joblib.load("../../models/diabetes_rf_pipeline.pkl")
svm_loaded = joblib.load("../../models/diabetes_svm_pipeline.pkl")

sample_df = X_test.iloc[[0]]

print("LR Prediction:", lr_loaded.predict(sample_df)[0])
print("RF Prediction:", rf_loaded.predict(sample_df)[0])
print("SVM Prediction:", svm_loaded.predict(sample_df)[0])


LR Prediction: 1
RF Prediction: 1
SVM Prediction: 1


 Final Comparison:
 
Logistic Regression

Accuracy: 71.4%

Recall (Diabetes = 1): 0.52

False Negatives: 26 ❌ (too many missed diabetics)

SVM

Accuracy: 75.3%

Recall (Diabetes = 1): 0.61

False Negatives: 21 ⚠️ (better than LR, still moderate)

Confusion Matrix:

[[83 17]
 [21 33]]

Random Forest

Accuracy: 77.3% (BEST)

Recall (Diabetes = 1): 0.63 (BEST) 

False Negatives: 20 (LOWEST) ✅

In [48]:
# Build Pipeline with SMOTE
rf_pipeline = ImbPipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("model", RandomForestClassifier(random_state=42))
])

In [49]:
# Hyperparameter Space
param_dist = {
    "model__n_estimators": [200, 300, 400, 500],
    "model__max_depth": [None, 10, 20, 30],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2"]
}

In [50]:
rf_search = RandomizedSearchCV(
    rf_pipeline,
    param_distributions=param_dist,
    n_iter=25,
    cv=5,
    scoring="recall",  # 🔥 Optimize for diabetic detection
    n_jobs=-1,
    random_state=42
)

In [51]:
rf_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('imputer',
                                              SimpleImputer(strategy='median')),
                                             ('smote', SMOTE(random_state=42)),
                                             ('model',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'model__max_depth': [None, 10, 20, 30],
                                        'model__max_features': ['sqrt', 'log2'],
                                        'model__min_samples_leaf': [1, 2, 4],
                                        'model__min_samples_split': [2, 5, 10],
                                        'model__n_estimators': [200, 300, 400,
                                                                500]},
                   random_state=42, scoring='recall')

In [52]:
print("Best Parameters:", rf_search.best_params_)
print("Best CV Recall:", rf_search.best_score_)

Best Parameters: {'model__n_estimators': 500, 'model__min_samples_split': 2, 'model__min_samples_leaf': 4, 'model__max_features': 'log2', 'model__max_depth': 30}
Best CV Recall: 0.7384274640088593


In [53]:
# Evaluate Best Model
best_rf = rf_search.best_estimator_

preds = best_rf.predict(X_test)
probs = best_rf.predict_proba(X_test)[:, 1]

print("\nImproved Random Forest Accuracy:", accuracy_score(y_test, preds))
print("\nClassification Report:\n", classification_report(y_test, preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, preds))
print("\nROC-AUC:", roc_auc_score(y_test, probs))


Improved Random Forest Accuracy: 0.7337662337662337

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.76      0.79       100
           1       0.61      0.69      0.64        54

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.72       154
weighted avg       0.74      0.73      0.74       154


Confusion Matrix:
 [[76 24]
 [17 37]]

ROC-AUC: 0.827037037037037


In [54]:
# Save Best Model
joblib.dump(best_rf, "../../models/diabetes_best_rf_pipeline.pkl")

['../../models/diabetes_best_rf_pipeline.pkl']

<!-- “I optimized for recall to reduce false negatives in diabetic detection. This slightly increased false positives, reducing accuracy marginally, but improved sensitivity — which is more critical in medical screening systems.” -->

##### "“I optimized for recall to reduce false negatives in diabetic detection. This slightly increased false positives, reducing accuracy marginally, but improved sensitivity — which is more critical in medical screening systems.”"

### "Build XGBoost Pipeline"

In [55]:
xgb_pipeline = ImbPipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("model", XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        use_label_encoder=False,
        random_state=42
    ))
])


### "Hyperparameter Tuning"

In [56]:
param_dist = {
    "model__n_estimators": [200, 300, 400],
    "model__max_depth": [3, 5, 7],
    "model__learning_rate": [0.01, 0.05, 0.1],
    "model__subsample": [0.8, 1.0],
    "model__colsample_bytree": [0.8, 1.0],
    "model__gamma": [0, 1, 5]
}

xgb_search = RandomizedSearchCV(
    xgb_pipeline,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring="recall",  # prioritize detecting diabetes
    n_jobs=-1,
    random_state=42
)

xgb_search.fit(X_train, y_train)

print("Best Parameters:", xgb_search.best_params_)
print("Best CV Recall:", xgb_search.best_score_)


c:\Users\Admin\OneDrive\Desktop\Health-App\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [12:03:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Best Parameters: {'model__subsample': 0.8, 'model__n_estimators': 300, 'model__max_depth': 3, 'model__learning_rate': 0.01, 'model__gamma': 0, 'model__colsample_bytree': 1.0}
Best CV Recall: 0.7616832779623477


Evaluate Best XGBoost Model

In [57]:
best_xgb = xgb_search.best_estimator_

preds = best_xgb.predict(X_test)
probs = best_xgb.predict_proba(X_test)[:, 1]

print("XGBoost Accuracy:", accuracy_score(y_test, preds))
print("\nClassification Report:\n", classification_report(y_test, preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, preds))
print("\nROC-AUC:", roc_auc_score(y_test, probs))


XGBoost Accuracy: 0.7532467532467533

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.72      0.79       100
           1       0.61      0.81      0.70        54

    accuracy                           0.75       154
   macro avg       0.74      0.77      0.74       154
weighted avg       0.78      0.75      0.76       154


Confusion Matrix:
 [[72 28]
 [10 44]]

ROC-AUC: 0.8268518518518518


In [59]:
# XGBoost reduced false negatives from:

# 24 (original RF)

# 17 (tuned RF)

# 🔥 10 (XGBoost)

# That is a major improvement.

# You are now detecting:

# 44 out of 54 diabetic patients
# (~81% sensitivity)

# For a medical screening model, that is strong.



In [60]:
# XGBoost increased:

# False Positives (28 vs 24 vs 16 earlier)

# But that is acceptable in medical screening.

# Why?

# Because:

# It is safer to wrongly flag a healthy person
# than to miss a sick patient.

# This is the correct medical bias

 ### "“XGBoost achieved the highest recall for diabetic cases, reducing false negatives significantly while maintaining stable ROC-AUC. Since medical screening prioritizes sensitivity over raw accuracy, XGBoost was selected as the final deployed model.”"

In [61]:
probs = best_xgb.predict_proba(X_test)[:, 1]

custom_preds = (probs > 0.40).astype(int)

print(classification_report(y_test, custom_preds))


              precision    recall  f1-score   support

           0       0.89      0.64      0.74       100
           1       0.56      0.85      0.68        54

    accuracy                           0.71       154
   macro avg       0.72      0.75      0.71       154
weighted avg       0.77      0.71      0.72       154



| Model               | Recall (1) | Accuracy | FN |
| ------------------- | ---------- | -------- | -- |
| Tuned RF            | 0.69       | 0.73     | 17 |
| XGB (0.5)           | 0.81       | 0.75     | 10 |
| XGB (0.4 threshold) | 🔥 0.85    | 0.71     | ~8 |


In [ ]:
# For academic “balanced metrics”:
# → Deploying XGBoost default threshold

# “I adjusted the classification threshold to increase sensitivity for diabetic detection. This reduced false negatives further, which is critical in medical screening, even though overall accuracy slightly decreased.”

In [62]:
joblib.dump(best_xgb, "../../models/diabetes_final_model.pkl")


['../../models/diabetes_final_model.pkl']